### ISSUE TITLE
descriptions.html updates

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/lib#1]
It seems that among all the changes made on the file "descriptions.html" some are not displayed online:
e.g.

```
<section id="ownership_statements">           
<h1>Ownership Statements</h1>            
<p>In the TST Project, we define an ownership statement as ...</p>
```

and most of the descriptions of the manuscripts collections.

**Comment by chchch** [comment]
This should be fixed now; let me know if there are still any missing.

**Comment by manufrancis** [comment]
Fine!  Thanks!
